
codes = {
    0: "clear sky",
    1: "mainly clear, partly cloudy, and overcast",
    2: "mainly clear, partly cloudy, and overcast",
    3: "mainly clear, partly cloudy, and overcast",
    45: "fog and depositing rime fog",
    48: "fog and depositing rime fog",
    51: "Drizzle : Light, moderate, and dense intensity",
    53: "Drizzle : Light, moderate, and dense intensity",
    55: "Drizzle : Light, moderate, and dense intensity",
    56: "Freezing Drizzle: Light and dense intensity",
    57: "Freezing Drizzle: Light and dense intensity",
    61: "Rain: slight, moderate and heavy intensity",
    63: "Rain: slight, moderate and heavy intensity",
    65: "Rain: slight, moderate and heavy intensity",
    66: "freezing rain:light and heavy intensity",
    67: "freezing rain:light and heavy intensity",
    71: "Snow fall : slight, moderate and heavy intensity",
    73: "Snow fall : slight, moderate and heavy intensity",
    75: "Snow fall : slight, moderate and heavy intensity",
    77: "snow grains",
    80: "Rain showers",
    81: "Rain showers",
    82: "Rain showers",
    85: "Snow showers",
    86: "Snow showers",
    95: "thunderstorm",
    96: "thunderstorm with slight and heavy hail",
    99: "thunderstorm with slight and heavy hail"
        }

functions = {
    0: clear_sky,
    1: mainly_clear,
    2: mainly_clear,
    3: mainly_clear,
    45: fog,
    48: fog,
    51: drizzle,
    53: drizzle,
    55: drizzle,
    56: freezing_drizzle,
    57: freezing_drizzle,
    61: rain,
    63: rain,
    65: rain,
    66: freezing_rain,
    67: freezing_rain,
    71: snow_fall,
    73: snow_fall,
    75: snow_fall,
    77: snow_grains,
    80: rain_showers,
    81: rain_showers,
    82: rain_showers,
    85: snow_showers,
    86: snow_showers,
    95: thunderstorm,
    96: thunderstorm_hail,
    99: thunderstorm_hail
        }